# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:10
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=32, unique=True, validators=[app.models.validate_external_id])),
            ],
        ),
        migrations.CreateModel(
            name='CampaignList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=32, validators=[app.models.validate_external_id])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CampaignClient')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Bounced', 'Bounced'), ('Deleted', 'Deleted'), ('Unconfirmed', 'Unconfirmed'), ('Unsubscribed', 'Unsubscribed')], default='Active', max_length=12)),
                ('lists', models.ManyToManyField(to='app.CampaignList')),
            ],
        ),
    ]
